baseURL = 'https://tbrixen.github.io/'
languageCode = 'en-us'
title = 'tbrixen'
theme = 'anatole'

summarylength = 10
enableEmoji = true

# Enable Chroma
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  title = 'tbrixen'
  author = 'Tobias Brixen'
  description = "Sharing my unfinished ideas in the online collaborative sandbox"
  profilePicture = "images/profile.png"
  #customCss = ["css/syntax.css"] # enable to use Chroma style
  contentratio = 0.8

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "http://github.com/tbrixen"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://dk.linkedin.com/in/tbrixen"

[params.umami]
serverURL = "analytics.umami.is"
id = "b1c6be44-f1ef-4886-862e-f468d2b074be"
trackerScriptName = "script.js"

[params.giscus]
repo = "tbrixen/tbrixen.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkxODQ4NDI1MQ=="
category = "Announcements"
categoryID = "DIC_kwDOARoMG84CXzE9"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

